hypoport/europace-productengine-api

api.json
beispiele/anfrage.json

Eigenvertrieb OSD: Lebenshaltungskosten des Antragstellers in HHR berücksichtigen
https://trello.com/c/1wd5AxWl/366-b-eigenvertrieb-osd-lebenshaltungskosten-des-antragstellers-in-hhr-ber%C3%BCcksichtigen

LebenshaltungsKostenMonatlich in Haushalt

---

api.json
beispiele/anfrage.json

https://trello.com/c/1HxXGga8/

RSV wird für FINMAS-PE enabled

---

api.json

https://trello.com/c/1HxXGga8/

RSV: angepasst FestBetragsVorgabeMitRatenschutzAufschlag

---

api.json

RSV: remove unnecessary attributes and types

---

beispiele/anfrage.json

response hasn't changed
https://trello.com/c/868RB27q

 add FremdRatenschutzInformationen to example request

---

api.json

https://github.com/hypoport/enabling-genopace/issues/5

FinanzierungsArt NACHFINANZIERUNG entfernen

---

api.json
beispiele/anfrage.json

Die LBSn können nun im Frontend den aus einem externen Tool bestimmten Beleihungswert eingeben.
Der soll an die PE weitergereicht werden.
https://finmas.atlassian.net/browse/ITDEV-50

Externe Beleihungswertvorgabe für Objekte

---

api.json
beispiele/anfrage.json

Förder-Typen und Förder-Modelle in der Anfrage (DarlehensOptionsTyp, FoerderOption, SingulaereFoerderOption, DarlehensTyp, FoerderDarlehenInformation in FremdDarlehenInformation)
https://trello.com/c/WLCdff5H/138-f%C3%B6rderdarlehen-in-papi-api

Integration Förderdarlehen in Api

---

.github/workflows/release-drafter.yml

Release Drafter Bugfix

---

api.json
beispiele/antwort.json

https://europace.atlassian.net/browse/PPK-893

Neues Feld zur Kennzeichnung von schnellen Angeboten (EP-Best) hinzugefügt

---

api.json
beispiele/antwort.json

https://europace.atlassian.net/browse/PPK-175
https://finmas.atlassian.net/browse/ITDEV-107

Bereitstellungszins-Plan auch für Finmas-PE

---

api.json

https://europace.atlassian.net/browse/PPK-175
https://finmas.atlassian.net/browse/ITDEV-107

Bereitstellungszins-Plan Typo Fix

---

api.json
beispiele/antwort.json

Api Erweiterung für KreditbetriebsVorgabe.

Füge Kreditbetriebsvorgabe zu api hinzu.

---

api.json
beispiele/anfrage.json
beispiele/antwort.json

[ITDEV-140]
Um Aufschläge rund um Tilgungssatzwechsel in Finmas PE umzusetzen (analog Speed: **PPK-1343**) müssen Anfrage + Antwort erweitert werden.
[ITDEV-140]: https://finmas.atlassian.net/browse/ITDEV-140

Erweiterung um relevante Daten Tilgungssatz-Wechsel

---

api.json
beispiele/antwort.json

Feld anzahlKostenfreieTilgungsSatzWechsel nicht im Angebot, sonst im Darlehen
https://finmas.atlassian.net/browse/ITDEV-140

Feld anzahlKostenfreieTilgungsSatzWechsel im Darlehen

---

api.json
beispiele/anfrage.json

JIRA: https://finmas.atlassian.net/browse/ITDEV-520

Darlehensnehmer um "email" und "telefonnummer" erweitert

---

api.json
beispiele/anfrage.json

https://finmas.atlassian.net/browse/ITDEV-530

Anfrage um "OneClickSpezifischeDaten" erweitert

---

api.json
beispiele/anfrage.json

Objekt um EnergieEffizienzAusweis und EndEnergieGeplantBeiModernisierung erweitert
https://finmas.atlassian.net/browse/ITDEV-617

Grüne Baufi

---

api.json
beispiele/anfrage.json

https://finmas.atlassian.net/browse/ITDEV-660

OneClickSpezifischeDaten um DokumentenKategorien erweitert

---

api.json
beispiele/anfrage.json

- versicherungsBeginn
- versicherungsEnde
- vertragsPartnerId
https://finmas.atlassian.net/browse/ITDEV-695
Bitte reviewen, megen und releasen.

FremdRatenschutzInformation erweitert

---

api.json
beispiele/antwort.json

Erweiterung der Antwort um Bearbeitungszeiten, damit auch die Finmas Produkte diese liefern können.

[MTV] Erweiterung der API um Bearbeitungszeiten

---

api.json
beispiele/anfrage.json

https://finmas.atlassian.net/browse/ITDEV-753
**Motivation**
Nebenkostenpauschale pro m² je nach Endenergie (Bedarf oder Verbrauch) in kWh/m²•a für eigengenutzte Wohnfläche.

WeiteresImmobilienVermoegen um EnergieEffizienzAusweis erweitert

---

api.json
beispiele/anfrage.json

Story: [ITDEV-710](https://finmas.atlassian.net/browse/ITDEV-710)
Neues Zusatzfeld, das in Finmas-PE gesondert angerechnet werden soll.
rel: https://github.com/hypoport/efi-baufismart-api/pull/328

Erweiterung EffektivZinsKosten um ratenschutzVersicherungsPraemieEinmalig

---

api.json
beispiele/antwort.json

closes [MTV-7731]
Um die Property `kontoCheck` auch für Finmas Produkte zu erhalten, soll diese Property hinzugefügt werden. Es dient der Identifikation von Angeboten, die das Feature Kontocheck aktiviert haben.
[MTV-7731]: https://europace.atlassian.net/browse/MTV-7731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[MTV-7731] added field kontocheck and example
